apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: default
data:
  # Configurações do Banco de Dados
  POSTGRES_DB: "auth_db"
  POSTGRES_USER: "carl_admin"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-auth:5432/auth_db"
  SPRING_DATASOURCE_USERNAME: "carl_admin"
