apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    
    # --- Configuração de CORS (Segurança) ---
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://site.carldev.online"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, OPTIONS" 
    
    # Limite de 20 request por segundo por IP"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
    nginx.ingress.kubernetes.io/limit-req-status-code: "429" 
    
    nginx.ingress.kubernetes.io/proxy-real-ip-cidr: "0.0.0.0/0"

spec:
  ingressClassName: nginx
  rules:
    - host: api.carldev.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 4000
